config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :profile, only: [:index]
  resources :posts, only: [:create] do
    resources :comments, only: [:index, :create]
    resource :likes, only: [:update]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  act_as_mentioner

  validates :content, presence: true

  belongs_to :post
  belongs_to :user

  def author
    "@#{self.user.username}"
  end
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }

  belongs_to :user
  belongs_to :post
end

app/models/mention_processor.rb
class MentionProcessor < MentionSystem::MentionProcessor
  def extract_mentioner_content(entity)
    entity.content
  end

  def find_mentionees_by_handles(*handles)
    User.where(username: handles)
  end
end

app/models/mention_processor_mailer.rb
class MentionProcessorMailer
  def initialize(entity)
    @entity = entity
  end

  def process
    users.each do |user|
      MentionMailer.with(user: user, entity: @entity).
                        mention.
                        deliver_now
    end
  end

  private
  def users
    MentionProcessor.new.process_mentions(@entity)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  act_as_mentioner
  validates :content, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked?(by_user)
    self.likes.where(user: by_user).any?
  end
end

app/models/user.rb
class User < ApplicationRecord
  act_as_mentionee

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :avatar_format
  validates :username, { presence: true, uniqueness: true }

  has_many :posts, dependent: :destroy
  has_one_attached :avatar

  before_validation :assign_username

  def resize_image
      resized_image = MiniMagick::Image.read(avatar.download)
      resized_image = resized_image.resize "400x400"
      v_filename = avatar.filename
      v_content_type = avatar.content_type
      avatar.purge
      avatar.attach(io: File.open(resized_image.path), filename:  v_filename, content_type: v_content_type)
  end

  def avatar_format
   return unless avatar.attached?
   if avatar.blob.content_type.start_with? 'image/'
     if avatar.blob.byte_size > 5.megabytes
       errors.add(:avatar, 'size needs to be less than 5MB')
       avatar.purge
     else
       resize_image
     end
    else
      avatar.purge
      errors.add(:avatar, 'needs to be an image')
    end
  end

  def assign_username
    self.username = self.email.split("@")[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(
        :username,
        :avatar,
        :email,
        :password,
        :password_confirmation,
        :current_password
      )
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = post.comments.order("created_at desc")
    respond_to do |format|
      format.js
    end
  end

  def create
    @comment = post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save!
      MentionMailerJob.perform_later(@comment)
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def post
    @post ||= Post.find(params[:post_id])
  end

  def comment_params
    params.permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all.map{ |u| [u.username, u.email] }
    @post = Post.new
    @posts = Post.includes(:comments, :likes).order("created_at desc")
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def update
    @post = Post.includes(:likes).find(params[:post_id])
    if params[:liked] == "false"
      @like = Like.create(post: @post, user: current_user)
    else
      Like.where(post: @post, user: current_user).destroy_all
    end
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      MentionMailerJob.perform_later(@post)
    end
    respond_to do |format|
      format.js
    end
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    #
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def post_liked_css_class(post)
    post.liked?(current_user) ? "fas" : "far"
  end
end

app/views/comments/_comment.html.erb
<div class="card p-3">
  <div class="js-single-comment">
    <div class="text-justify">
      <div class="">
        <p>
          <%= comment.content.html_safe %>
        </p>
        <p class="text-right">
          <%= comment.author %>
          <%- if comment.user.avatar.attached? %>
            <%= image_tag comment.user.avatar.variant(resize: "30x30") %>
          <%-end%>
          <br>
          <%= comment.created_at.strftime("%b, %d %y") %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="js-new-comment hidden">
  <p>New comment:</p>
  <%= form_with(url: post_comments_path(post_id: post.id)) do |f| %>
    <%= f.text_area :content, class: "js-new-message-content" %>
    <%= f.submit "send", class: "btn btn-primary", style: "font-size: 17px;" %>
  <%- end %>
</div>

app/views/comments/create.js.erb
var postContainer = $(".js-comments-container-<%=@post.id%>").parents(".js-post-container");
$(".js-comments-container-<%=@post.id%>").prepend("<%= j(render partial: 'comments/comment', locals: {comment: @comment, post: @post} ) %>")

postContainer.find(".js-new-message-contnet").val("");
postContainer.find(".js-get-comments-link").addClass("hidden");
postContainer.find(".js-hide-comments-link").removeClass("hidden");
postContainer.find(".js-new-comment").removeClass("hidden");
postContainer.find(".fr-element.fr-view").find("p").html("");

app/views/comments/index.js.erb
$( document ).ready(function() {
  var postContainer = $(".js-comments-container-<%=@post.id%>").parents(".js-post-container");
  $(".js-comments-container-<%=@post.id%>").removeClass("hidden");
  $(".js-comments-container-<%=@post.id%>").prepend("<%= j(render partial: 'comments/comment', collection: @comments, locals: {post: @post} ) %>");

  postContainer.find(".js-get-comments-link").addClass("hidden");
  postContainer.find(".js-hide-comments-link").removeClass("hidden");
  postContainer.find(".js-new-comment").removeClass("hidden");

  new FroalaEditor('.js-new-message-content', {
    toolbarButtons: [['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript'],
                     ['fontFamily', 'fontSize']]
  });
});

app/views/home/_user_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <%- @users.each do |u| %>
      <tr>
        <th ><%= u[0]%></th>
        <th ><%= u[1]%></th>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/home/index.html.erb
<div class="col">
  <h2> POSTS </h2>
  <div>
    <%= render partial: "posts/form" %>
  </div>
  <div class="js-posts-list">
    <%= render partial: "posts/post", collection: @posts %>
  </div>
</div>
<div class="col">
  <%= render partial: "home/user_list" %>
</div>

<%= javascript_include_tag "comments/index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="turbolinks-cache-control" content="no-preview">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src = "https://cdnjs.cloudflare.com/ajax/libs/froala-editor/3.2.6/js/froala_editor.min.js"></script>
  </head>
  <body>
    <div  class="container"">
      <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <ul class="navbar-nav ml-auto ml-md-0">
          <li>
            <%= link_to "Home", root_path, class: "navbar-brand" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if user_signed_in? %>
                <%- if current_user.avatar.attached? %>
                  <%= image_tag current_user.avatar.variant(resize: "30x30") %>
                <%-else%>
                  <i class="fas fa-user"></i>
                <%-end %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              <% else %>
                <i class="fas fa-user"></i>
              <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </nav>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/likes/update.js.erb
var postContainer = $(".js-comments-container-<%=@post.id%>").parents(".js-post-container");
if("<%= @like.present? %>" == "true" ){
  postContainer.find(".js-like-post").find("i").removeClass("far").addClass("fas");
  postContainer.find(".js-like-post").data("liked", "true");
}else{
  postContainer.find(".js-like-post").find("i").removeClass("fas").addClass("far");
  postContainer.find(".js-like-post").data("liked", "false");
}
postContainer.find(".js-like-post").find("span").html("<%= @post.reload.likes.size %>");

app/views/posts/_form.html.erb
<div class="js-new-post border p-3">
  <p>New Post:</p>
  <%= form_with(model: @post, url: posts_path) do |f| %>
    <%= f.text_area :content, class: "js-new-post-content" %>
    <%= f.submit "send", class: "btn btn-primary", style: "font-size: 17px;" %>
  <%- end %>
</div>

<%= javascript_include_tag "posts/new" %>

app/views/posts/_like.html.erb
<div>
  <%= link_to "javascript:;", class: "js-like-post", data: { url: post_likes_path(post), liked: post.liked?(current_user) } do %>
    <span> <%= post.likes.size %> </span>
    <i class="<%= post_liked_css_class(post) %> fa-heart"></i>
  <%- end %>
</div>

app/views/posts/_post.html.erb
<div class="js-post-container" data-post-id= <%= post.id %> >
  <div class="card p-3 gap-3 mt-4">
    <div>
      <%= post.content.html_safe %>
    </div>
    <div>
      <%= render partial: "posts/single_post_comments", locals: { post: post } %>
      <%= render partial: "posts/like", locals: { post: post } %>
    </div>
    <div class="js-comments-container-<%= post.id %> hidden">
      <!-- rendered partial from comments/index.js.erb -->
    </div>
    <%= render partial: "comments/form", locals: { post: post } %>
  </div>
</div>

app/views/posts/_single_post_comments.html.erb
<div>
  <%= link_to "#{post.comments.size} Comments", post_comments_path(post_id: post), class: "js-get-comments-link", data: { post_id: post.id} %>
  <%= link_to "Hide comments", "javascript:;", class: "js-hide-comments-link hidden", data: { post_id: post.id } %>
  <br>
</div>

app/views/posts/create.js.erb
var postList = $(".js-posts-list");
postList.prepend("<%= j(render partial: 'posts/post', locals: { post: @post } ) %>")
$(".js-new-post").find(".fr-element.fr-view").find("p").html("");